### ISSUE TITLE
Do you plan to make forwarding addresses into etcd service discovery?

### ISSUE THREAD

**Issue by wisonlau** [oortfy/api-gateway#2]
https://github.com/oortfy/api-gateway/blob/221e9051d0bd4526176fbe01f3b24b8da7bd8fee/example/routes.yaml#L9

Example:

config.yaml
```yaml
etcd:
  hosts:
    - 127.0.0.1:2379
```

routes.yaml
```yaml
routes:
  - path: "/scanjobmanager"
    upstream: "http://localhost:8001"
    methods: ["GET", "POST", "PUT", "DELETE"]
    load_balancing:
      method: "round_robin"
      health_check: true
      driver: static # todo
      discoveries: # todo
      endpoints:
        - "http://localhost:8001"
        - "http://localhost:8002"
      health_check_config:
        path: "/scanjobmanager/health"
        interval: 10
        timeout: 2

  # etcd service discovery
  - path: "/user"
    upstream: "" # todo
    methods: ["GET", "POST", "PUT", "DELETE"]
    load_balancing:
      method: "round_robin"
      health_check: true
      driver: etcd # todo
      discoveries: # todo
        - name: user.rpc # server_name
          enable: true
          fail-limit: 3
      endpoints:
      health_check_config:
        path: "/user/health"
        interval: 10
        timeout: 2
    rate_limit:
      requests_per_minute: 1000
```

[etcd discovery client](https://github.com/Bingjian-Zhu/etcd-example/blob/1005223ede7fff1187e5ffa1b02e0f2d9ed6ca1b/3-etcd-service-discovery/discovery/discovery.go#L80)

**Comment by wisonlau** [comment]
path supports regex

- prefix: /api/echo/*
- path: /api/echo/hello
- regex: /api/echo/[a-z]+
- restful: /api/echo/{name}

```yaml
routes:
  - path: "/order/*"
    upstream: "http://localhost:8001"
    methods: ["GET", "POST", "PUT", "DELETE"]
    load_balancing:
      method: "round_robin"
      health_check: true
      driver: static # todo
      discoveries: # todo
      endpoints:
        - "http://localhost:8001"
        - "http://localhost:8002"
      health_check_config:
        path: "/order/health"
        interval: 10
        timeout: 2
```
